---
version: '3'
services:
  freqtrade:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.develop"
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    container_name: freqtrade
